/*
 * Copyright (c) 2018, NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Generated by erpcgen 1.5.0 on Mon Nov 13 15:29:32 2017.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_crc16_h_)
#define _erpc_crc16_h_

#if !defined(ERPC_GENERATED_CRC)
#define ERPC_GENERATED_CRC 47304
#else
#error "Macro 'ERPC_GENERATED_CRC' shouldn't be defined at this moment."
#endif

#endif /* _erpc_crc16_h_ */

